/**
 * Practical English vocabulary word pool for the Daily Vocabulary feature.
 *
 * Selection criteria for every word:
 *  ✅ High real-world frequency (appears regularly in daily/professional English)
 *  ✅ Genuinely useful in conversations, emails, meetings, or writing
 *  ✅ Learner can realistically use the word today
 *  ✅ Transferable across multiple situations
 *  ❌ NOT selected merely because it is rare, academic, or sounds impressive
 */

export interface WordEntry {
  word: string;
  /** How / where the word is most usefully applied */
  context: string;
}

export const VOCABULARY_WORD_POOL: WordEntry[] = [
  // ── Conversation & expressing yourself ──────────────────────────────────────
  { word: "clarify",      context: "Conversations / Meetings" },
  { word: "mention",      context: "Conversations / Emails" },
  { word: "explain",      context: "Conversations / Teaching" },
  { word: "describe",     context: "Conversations / Writing" },
  { word: "express",      context: "Conversations / Emails" },
  { word: "admit",        context: "Conversations / Honesty" },
  { word: "agree",        context: "Conversations / Discussions" },
  { word: "disagree",     context: "Conversations / Discussions" },
  { word: "confirm",      context: "Emails / Meetings" },
  { word: "remind",       context: "Conversations / Emails" },
  { word: "respond",      context: "Emails / Conversations" },
  { word: "react",        context: "Conversations / Situations" },
  { word: "suggest",      context: "Conversations / Meetings" },
  { word: "recommend",    context: "Conversations / Advice" },
  { word: "prefer",       context: "Conversations / Choices" },
  { word: "insist",       context: "Conversations / Arguments" },
  { word: "hesitate",     context: "Conversations / Decisions" },
  { word: "assume",       context: "Conversations / Thinking" },
  { word: "realize",      context: "Conversations / Situations" },
  { word: "notice",       context: "Conversations / Observations" },

  // ── Workplace & professional communication ──────────────────────────────────
  { word: "prioritize",   context: "Workplace / Time Management" },
  { word: "coordinate",   context: "Workplace / Teams" },
  { word: "collaborate",  context: "Workplace / Teams" },
  { word: "delegate",     context: "Workplace / Management" },
  { word: "implement",    context: "Workplace / Projects" },
  { word: "evaluate",     context: "Workplace / Reviews" },
  { word: "schedule",     context: "Workplace / Planning" },
  { word: "deadline",     context: "Workplace / Projects" },
  { word: "feedback",     context: "Workplace / Reviews" },
  { word: "update",       context: "Workplace / Communication" },
  { word: "approach",     context: "Workplace / Problem Solving" },
  { word: "handle",       context: "Workplace / Situations" },
  { word: "manage",       context: "Workplace / Responsibilities" },
  { word: "address",      context: "Workplace / Issues" },
  { word: "resolve",      context: "Workplace / Problems" },
  { word: "achieve",      context: "Workplace / Goals" },
  { word: "deliver",      context: "Workplace / Results" },
  { word: "track",        context: "Workplace / Progress" },
  { word: "review",       context: "Workplace / Documents" },
  { word: "submit",       context: "Workplace / Tasks" },
  { word: "complete",     context: "Workplace / Tasks" },
  { word: "assign",       context: "Workplace / Teams" },
  { word: "report",       context: "Workplace / Communication" },
  { word: "present",      context: "Workplace / Meetings" },
  { word: "discuss",      context: "Workplace / Meetings" },
  { word: "involve",      context: "Workplace / Collaboration" },
  { word: "require",      context: "Workplace / Conditions" },
  { word: "ensure",       context: "Workplace / Quality" },
  { word: "approve",      context: "Workplace / Decisions" },
  { word: "reject",       context: "Workplace / Decisions" },
  { word: "propose",      context: "Workplace / Meetings" },

  // ── Emails & written communication ─────────────────────────────────────────
  { word: "attach",       context: "Emails / Documents" },
  { word: "forward",      context: "Emails / Communication" },
  { word: "summarize",    context: "Emails / Reports" },
  { word: "outline",      context: "Emails / Planning" },
  { word: "draft",        context: "Emails / Writing" },
  { word: "acknowledge",  context: "Emails / Responses" },
  { word: "request",      context: "Emails / Communication" },
  { word: "provide",      context: "Emails / Information" },
  { word: "refer",        context: "Emails / Documents" },
  { word: "include",      context: "Emails / Details" },
  { word: "exclude",      context: "Emails / Conditions" },

  // ── Describing quality & performance ────────────────────────────────────────
  { word: "accurate",     context: "Descriptions / Work Quality" },
  { word: "reliable",     context: "Descriptions / People / Products" },
  { word: "efficient",    context: "Descriptions / Work / Systems" },
  { word: "flexible",     context: "Descriptions / Schedules / People" },
  { word: "relevant",     context: "Descriptions / Information" },
  { word: "effective",    context: "Descriptions / Methods / People" },
  { word: "appropriate",  context: "Descriptions / Behavior / Content" },
  { word: "reasonable",   context: "Descriptions / Decisions / Requests" },
  { word: "significant",  context: "Descriptions / Importance" },
  { word: "specific",     context: "Descriptions / Instructions" },
  { word: "available",    context: "Descriptions / Schedules / Items" },
  { word: "necessary",    context: "Descriptions / Requirements" },
  { word: "suitable",     context: "Descriptions / Choices / Options" },
  { word: "consistent",   context: "Descriptions / Behavior / Work" },
  { word: "practical",    context: "Descriptions / Solutions / Ideas" },
  { word: "capable",      context: "Descriptions / People / Skills" },
  { word: "responsible",  context: "Descriptions / People / Tasks" },
  { word: "productive",   context: "Descriptions / Work / Days" },
  { word: "confident",    context: "Descriptions / People / Tone" },
  { word: "thorough",     context: "Descriptions / Work / Reviews" },

  // ── Decisions & thinking ────────────────────────────────────────────────────
  { word: "consider",     context: "Thinking / Decisions" },
  { word: "decide",       context: "Decisions / Actions" },
  { word: "determine",    context: "Decisions / Analysis" },
  { word: "justify",      context: "Decisions / Arguments" },
  { word: "analyze",      context: "Thinking / Research" },
  { word: "identify",     context: "Thinking / Problem Solving" },
  { word: "compare",      context: "Thinking / Choices" },
  { word: "predict",      context: "Thinking / Planning" },
  { word: "estimate",     context: "Thinking / Planning" },
  { word: "examine",      context: "Thinking / Research" },
  { word: "verify",       context: "Thinking / Checking" },
  { word: "anticipate",   context: "Thinking / Planning" },
  { word: "reflect",      context: "Thinking / Self-Improvement" },
  { word: "reconsider",   context: "Thinking / Decisions" },
  { word: "evaluate",     context: "Thinking / Assessment" },

  // ── Describing situations & problems ────────────────────────────────────────
  { word: "concern",      context: "Situations / Issues" },
  { word: "issue",        context: "Situations / Problems" },
  { word: "challenge",    context: "Situations / Difficulties" },
  { word: "obstacle",     context: "Situations / Problems" },
  { word: "opportunity",  context: "Situations / Possibilities" },
  { word: "situation",    context: "Situations / Context" },
  { word: "condition",    context: "Situations / Circumstances" },
  { word: "impact",       context: "Situations / Effects" },
  { word: "consequence",  context: "Situations / Effects" },
  { word: "benefit",      context: "Situations / Advantages" },
  { word: "risk",         context: "Situations / Planning" },
  { word: "limitation",   context: "Situations / Constraints" },
  { word: "pressure",     context: "Situations / Stress" },
  { word: "progress",     context: "Situations / Work" },
  { word: "outcome",      context: "Situations / Results" },
  { word: "result",       context: "Situations / Work" },

  // ── Growth & action ─────────────────────────────────────────────────────────
  { word: "improve",      context: "Growth / Work" },
  { word: "develop",      context: "Growth / Skills / Projects" },
  { word: "learn",        context: "Growth / Education" },
  { word: "adapt",        context: "Growth / Change" },
  { word: "adjust",       context: "Growth / Change" },
  { word: "grow",         context: "Growth / Skills" },
  { word: "focus",        context: "Growth / Productivity" },
  { word: "commit",       context: "Growth / Goals" },
  { word: "motivate",     context: "Growth / Teams" },
  { word: "encourage",    context: "Growth / People" },
  { word: "support",      context: "Growth / Teams / People" },
  { word: "maintain",     context: "Growth / Consistency" },
  { word: "sustain",      context: "Growth / Effort" },
  { word: "overcome",     context: "Growth / Challenges" },
  { word: "persist",      context: "Growth / Effort" },
  { word: "prepare",      context: "Growth / Planning" },
  { word: "practice",     context: "Growth / Learning" },

  // ── Relationships & teamwork ─────────────────────────────────────────────────
  { word: "communicate",  context: "Teamwork / Relationships" },
  { word: "cooperate",    context: "Teamwork / Groups" },
  { word: "negotiate",    context: "Teamwork / Business" },
  { word: "convince",     context: "Teamwork / Communication" },
  { word: "persuade",     context: "Teamwork / Arguments" },
  { word: "appreciate",   context: "Relationships / Gratitude" },
  { word: "respect",      context: "Relationships / Values" },
  { word: "trust",        context: "Relationships / Teams" },
  { word: "depend",       context: "Relationships / Reliability" },
  { word: "assist",       context: "Relationships / Help" },
  { word: "share",        context: "Relationships / Information" },
  { word: "involve",      context: "Relationships / Inclusion" },
  { word: "engage",       context: "Relationships / Participation" },
  { word: "connect",      context: "Relationships / People" },

  // ── Describing time & tasks ──────────────────────────────────────────────────
  { word: "urgent",       context: "Time / Tasks" },
  { word: "delay",        context: "Time / Planning" },
  { word: "postpone",     context: "Time / Planning" },
  { word: "immediate",    context: "Time / Urgency" },
  { word: "temporary",    context: "Time / Situations" },
  { word: "permanent",    context: "Time / Situations" },
  { word: "frequent",     context: "Time / Patterns" },
  { word: "occasional",   context: "Time / Patterns" },
  { word: "ongoing",      context: "Time / Projects" },
  { word: "upcoming",     context: "Time / Planning" },
  { word: "current",      context: "Time / Status" },
  { word: "previous",     context: "Time / History" },

  // ── Common adjectives for professional context ───────────────────────────────
  { word: "brief",        context: "Writing / Communication" },
  { word: "clear",        context: "Writing / Communication" },
  { word: "direct",       context: "Communication / Tone" },
  { word: "detailed",     context: "Writing / Instructions" },
  { word: "thorough",     context: "Work / Quality" },
  { word: "formal",       context: "Communication / Tone" },
  { word: "informal",     context: "Communication / Tone" },
  { word: "positive",     context: "Attitude / Communication" },
  { word: "critical",     context: "Thinking / Feedback" },
  { word: "objective",    context: "Thinking / Decisions" },
  { word: "transparent",  context: "Communication / Trust" },
  { word: "straightforward", context: "Communication / Clarity" },

  // ── Slightly advanced but highly practical ───────────────────────────────────
  { word: "acknowledge",  context: "Emails / Conversations" },
  { word: "emphasize",    context: "Communication / Presentations" },
  { word: "highlight",    context: "Communication / Reports" },
  { word: "indicate",     context: "Communication / Data" },
  { word: "demonstrate",  context: "Communication / Work" },
  { word: "establish",    context: "Workplace / Processes" },
  { word: "initiate",     context: "Workplace / Projects" },
  { word: "monitor",      context: "Workplace / Progress" },
  { word: "optimize",     context: "Workplace / Efficiency" },
  { word: "simplify",     context: "Work / Communication" },
  { word: "streamline",   context: "Work / Processes" },
  { word: "facilitate",   context: "Meetings / Collaboration" },
  { word: "contribute",   context: "Teamwork / Projects" },
  { word: "achieve",      context: "Goals / Work" },
  { word: "generate",     context: "Work / Ideas" },
  { word: "integrate",    context: "Work / Systems" },
  { word: "coordinate",   context: "Work / Teams" },
  { word: "allocate",     context: "Work / Resources" },
  { word: "document",     context: "Work / Records" },
  { word: "validate",     context: "Work / Quality" },
];

/**
 * Returns a deterministic but shuffled list of word candidates for a given date (YYYY-MM-DD),
 * excluding words that have already been used on previous days.
 *
 * The same date always produces the same shuffle order, ensuring
 * if generation is retried on the same day the same candidates are tried first.
 */
export function getWordCandidatesForDate(
  date: string,
  usedWords: Set<string>
): WordEntry[] {
  // Simple seeded value from the date characters
  const seed = date.split("").reduce((acc, ch) => acc + ch.charCodeAt(0), 0);

  const available = VOCABULARY_WORD_POOL.filter(
    (entry) => !usedWords.has(entry.word.toLowerCase())
  );

  // Fisher-Yates shuffle with LCG-based seeded random
  const arr = [...available];
  let s = seed;
  const rand = () => {
    s = (s * 1664525 + 1013904223) & 0xffffffff;
    return (s >>> 0) / 0xffffffff;
  };

  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }

  return arr;
}

export interface FallbackWordData {
  partOfSpeech: string;
  englishMeaning: string;
  hindiMeaning: string;
  exampleSentence: string;
  pronunciation: string;
  synonyms: string[];
}

export const BUILTIN_WORD_DETAILS: Record<string, FallbackWordData> = {
  clarify: {
    partOfSpeech: "verb",
    englishMeaning: "To make a statement or situation less confused and more comprehensible.",
    hindiMeaning: "स्पष्ट करना",
    exampleSentence: "Could you please clarify your main objective during today's meeting?",
    pronunciation: "/ˈklær.ə.faɪ/",
    synonyms: ["explain", "simplify", "elucidate"],
  },
  perspective: {
    partOfSpeech: "noun",
    englishMeaning: "A particular attitude toward or way of regarding something; a point of view.",
    hindiMeaning: "दृष्टिकोण / नज़रिया",
    exampleSentence: "She shared a valuable perspective on the project timeline.",
    pronunciation: "/pəˈspek.tɪv/",
    synonyms: ["viewpoint", "outlook", "standpoint"],
  },
  collaborate: {
    partOfSpeech: "verb",
    englishMeaning: "To work jointly with others on an activity or project.",
    hindiMeaning: "सहयोग करना / मिलकर काम करना",
    exampleSentence: "Our teams collaborate closely to deliver great results.",
    pronunciation: "/kəˈlæb.ə.reɪt/",
    synonyms: ["cooperate", "partner", "team up"],
  },
  efficient: {
    partOfSpeech: "adjective",
    englishMeaning: "Achieving maximum productivity with minimum wasted effort or expense.",
    hindiMeaning: "कुशल / कार्यक्षम",
    exampleSentence: "We need an efficient process for handling customer feedback.",
    pronunciation: "/ɪˈfɪʃ.ənt/",
    synonyms: ["productive", "effective", "organized"],
  },
  prioritize: {
    partOfSpeech: "verb",
    englishMeaning: "To arrange or handle items in order of importance.",
    hindiMeaning: "प्राथमिकता देना",
    exampleSentence: "Please prioritize urgent tasks before starting new projects.",
    pronunciation: "/praɪˈɒr.ɪ.taɪz/",
    synonyms: ["rank", "order", "emphasize"],
  },
  coordinate: {
    partOfSpeech: "verb",
    englishMeaning: "To bring different elements into a complex activity or relationship into efficient organization.",
    hindiMeaning: "तालमेल बिठाना / समन्वय करना",
    exampleSentence: "She will coordinate the schedule with all team members.",
    pronunciation: "/koʊˈɔːr.dɪ.neɪt/",
    synonyms: ["organize", "integrate", "align"],
  },
  implement: {
    partOfSpeech: "verb",
    englishMeaning: "To put a decision, plan, or agreement into effect.",
    hindiMeaning: "लागू करना / कार्यान्वित करना",
    exampleSentence: "The company plans to implement the new policy next month.",
    pronunciation: "/ˈɪm.plɪ.ment/",
    synonyms: ["execute", "apply", "enforce"],
  },
  evaluate: {
    partOfSpeech: "verb",
    englishMeaning: "To form an idea of the amount, number, or value of something; to assess.",
    hindiMeaning: "मूल्यांकन करना",
    exampleSentence: "We need to evaluate the results of the marketing campaign.",
    pronunciation: "/ɪˈvæl.ju.eɪt/",
    synonyms: ["assess", "judge", "appraise"],
  },
  schedule: {
    partOfSpeech: "verb",
    englishMeaning: "To plan an event or activity for a specific time.",
    hindiMeaning: "समय निर्धारित करना / कार्यसूची बनाना",
    exampleSentence: "Let's schedule a brief follow-up call tomorrow afternoon.",
    pronunciation: "/ˈskedʒ.uːl/",
    synonyms: ["plan", "book", "arrange"],
  },
  briefly: {
    partOfSpeech: "adverb",
    englishMeaning: "For a short time; in a quick and concise manner.",
    hindiMeaning: "संक्षेप में",
    exampleSentence: "Let me briefly explain the main updates.",
    pronunciation: "/ˈbriːf.li/",
    synonyms: ["concisely", "shortly", "in short"],
  },
};

export const HINDI_DICTIONARY: Record<string, string> = {
  clarify: "स्पष्ट करना / साफ-साफ बताना",
  mention: "उल्लेख करना / ज़िक्र करना",
  explain: "समझाना / विवरण देना",
  describe: "वर्णन करना / बताना",
  express: "व्यक्त करना / प्रकट करना",
  admit: "स्वीकार करना / मानना",
  agree: "सहमत होना / मानना",
  disagree: "असहमत होना",
  confirm: "पुष्टि करना / पक्का करना",
  remind: "याद दिलाना",
  respond: "प्रतिक्रिया देना / उत्तर देना",
  react: "प्रतिक्रिया देना",
  suggest: "सुझाव देना",
  recommend: "सिफारिश करना / सलाह देना",
  prefer: "पसंद करना / प्राथमिकता देना",
  insist: "आग्रह करना / ज़ोर देना",
  hesitate: "हिचकिचाना / संकोच करना",
  assume: "मान लेना / कल्पना करना",
  realize: "एहसास होना / महसूस होना",
  notice: "ध्यान देना / देखना",
  prioritize: "प्राथमिकता देना",
  coordinate: "तालमेल बिठाना / समन्वय करना",
  collaborate: "सहयोग करना / मिलकर काम करना",
  delegate: "सौंपना / अधिकार देना",
  implement: "लागू करना / कार्यान्वित करना",
  evaluate: "मूल्यांकन करना / जांचना",
  schedule: "समय निर्धारित करना / कार्यसूची बनाना",
  deadline: "अंतिम समयसीमा",
  feedback: "प्रतिक्रिया / राय",
  update: "अद्यतन / ताज़ा जानकारी देना",
  approach: "दृष्टिकोण / तरीक़ा",
  handle: "संभालना / निपटना",
  manage: "प्रबंध करना / संभालना",
  address: "ध्यान देना / संबोधित करना",
  resolve: "हल करना / सुलझाना",
  achieve: "हासिल करना / प्राप्त करना",
  deliver: "प्रदान करना / पहुंचाना",
  track: "निगरानी रखना / ट्रैक करना",
  review: "समीक्षा करना / पुनः जांचना",
  submit: "जमा करना / प्रस्तुत करना",
  complete: "पूरा करना",
  assign: "सौंपना / काम देना",
  report: "रिपोर्ट देना / विवरण देना",
  present: "प्रस्तुत करना / पेश करना",
  discuss: "चर्चा करना / बातचीत करना",
  involve: "शामिल करना",
  require: "आवश्यकता होना / ज़रूरत होना",
  ensure: "सुनिश्चित करना",
  approve: "स्वीकृत करना / मंज़ूरी देना",
  reject: "अस्वीकार करना / ख़ारिज करना",
  propose: "प्रस्ताव रखना",
  attach: "संलग्न करना / जोड़ना",
  forward: "आगे भेजना",
  summarize: "संक्षेप में बताना",
  outline: "रूपरेखा तैयार करना",
  draft: "मसौदा तैयार करना",
  acknowledge: "स्वीकार करना / रसीद देना",
  request: "अनुरोध करना",
  provide: "प्रदान करना / उपलब्ध कराना",
  refer: "संदर्भ देना",
  include: "शामिल करना",
  exclude: "बाहर रखना / छोड़ना",
  accurate: "सटीक / बिल्कुल सही",
  reliable: "विश्वसनीय / भरोसेमंद",
  efficient: "कुशल / कार्यक्षम",
  flexible: "लचीला / परिवर्तनशील",
  relevant: "प्रासंगिक / उपयुक्त",
  effective: "प्रभावी / असरदार",
  appropriate: "उपयुक्त / उचित",
  reasonable: "उचित / तर्कसंगत",
  significant: "महत्वपूर्ण / काफ़ी बड़ा",
  specific: "विशिष्ट / ख़ास",
  available: "उपलब्ध / मौजूद",
  necessary: "ज़रूरी / आवश्यक",
  suitable: "उपयुक्त / योग्य",
  consistent: "लगातार / एकसमान",
  practical: "व्यावहारिक",
  capable: "सक्षम / योग्य",
  responsible: "ज़िम्मेदार",
  productive: "उत्पादक / फलदायी",
  confident: "आत्मविश्वासी / आश्वस्त",
  thorough: "पूरा / गहन",
  consider: "विचार करना / ध्यान में रखना",
  decide: "फैसला करना / निर्णय लेना",
  determine: "तय करना / निर्धारित करना",
  justify: "उचित ठहराना",
  analyze: "विश्लेषण करना",
  identify: "पहचानना / चिन्हित करना",
  compare: "तुलना करना",
  predict: "भविष्यवाणी करना / अनुमान लगाना",
  estimate: "अनुमान लगाना",
  examine: "जांच करना / परीक्षण करना",
  verify: "सत्यापित करना / जांचना",
  anticipate: "पूर्वानुमान लगाना",
  reflect: "विचार करना",
  reconsider: "पुनर्विचार करना",
  concern: "चिंता / मामला",
  issue: "मुद्दा / समस्या",
  challenge: "चुनौती",
  obstacle: "बाधा / रुकावट",
  opportunity: "अवसर / मौक़ा",
  situation: "स्थिति / परिस्थिति",
  condition: "शर्त / अवस्था",
  impact: "प्रभाव / असर",
  consequence: "परिणाम / नतीजा",
  benefit: "लाभ / फ़ायदा",
  risk: "जोखिम / ख़तरा",
  limitation: "सीमा / पाबंदी",
  pressure: "दबाव",
  progress: "प्रगति / उन्नति",
  outcome: "परिणाम / नतीजा",
  result: "परिणाम / नतीजा",
  improve: "सुधार करना / बेहतर बनाना",
  develop: "विकसित करना",
  learn: "सीखना",
  adapt: "अनुकूल बनना / ढलना",
  adjust: "समायोजित करना",
  grow: "बढ़ना / विकास करना",
  focus: "ध्यान केंद्रित करना",
  commit: "प्रतिबद्ध होना",
  motivate: "प्रेरित करना",
  encourage: "प्रोत्साहित करना",
  support: "समर्थन करना / मदद देना",
  maintain: "बनाए रखना",
  sustain: "कायम रखना",
  overcome: "पार पाना / दूर करना",
  persist: "दृढ़ रहना",
  prepare: "तैयारी करना",
  practice: "अभ्यास करना",
  communicate: "बातचीत करना / संवाद करना",
  cooperate: "सहयोग करना",
  negotiate: "समझौता करना / बातचीत करके तय करना",
  convince: "समझाना / राज़ी करना",
  persuade: "मनाना / राज़ी करना",
  appreciate: "सराहना करना / कद्र करना",
  respect: "सम्मान करना / आदर करना",
  trust: "विश्वास करना / भरोसा करना",
  depend: "निर्भर होना",
  assist: "सहायता करना / मदद करना",
  share: "साझा करना / बांटना",
  engage: "शामिल होना / जुड़ना",
  connect: "जोड़ना / जुड़ना",
  urgent: "अत्यंत आवश्यक / तुरंत",
  delay: "देरी / विलंब",
  postpone: "स्थगित करना / टालना",
  immediate: "तत्काल / तुरंत",
  temporary: "अस्थायी",
  permanent: "स्थायी / पक्का",
  frequent: "बार-बार होने वाला",
  occasional: "कभी-कभार होने वाला",
  ongoing: "चल रहा / जारी",
  upcoming: "आगामी / आने वाला",
  current: "वर्तमान / फ़िलहाल",
  previous: "पिछला / पूर्व",
  brief: "संक्षिप्त / छोटा",
  clear: "स्पष्ट / साफ़",
  direct: "सीधा / प्रत्यक्ष",
  detailed: "विस्तृत / ब्योरेवार",
  formal: "औपचारिक",
  informal: "अनौपचारिक",
  positive: "सकारात्मक",
  critical: "गंभीर / आलोचनात्मक",
  objective: "निष्पक्ष / उद्देश्य",
  transparent: "पारदर्शी / साफ़",
  straightforward: "सीधा-साधा / सरल",
  emphasize: "ज़ोर देना",
  highlight: "मुख्य बिंदु उजागर करना",
  indicate: "संकेत देना / दर्शाना",
  demonstrate: "प्रदर्शन करना / दिखाना",
  establish: "स्थापित करना",
  initiate: "शुरुआत करना / पहल करना",
  monitor: "निगरानी रखना",
  optimize: "अनुकूलित करना / सर्वश्रेष्ठ बनाना",
  simplify: "सरल बनाना",
  streamline: "सुव्यवस्थित करना",
  facilitate: "आसान बनाना / सुगम बनाना",
  contribute: "योगदान देना",
  generate: "उत्पन्न करना / बनाना",
  integrate: "एकीकृत करना / जोड़ना",
  allocate: "आवंटित करना",
  document: "दर्ज करना / दस्तावेज़ बनाना",
  validate: "प्रमाणित करना / जांचना",
  perspective: "दृष्टिकोण / नज़रिया",
  briefly: "संक्षेप में",
};

export function getFallbackWordDetails(word: string): FallbackWordData {
  const key = word.toLowerCase().trim();
  if (BUILTIN_WORD_DETAILS[key]) {
    return BUILTIN_WORD_DETAILS[key];
  }

  const entry = VOCABULARY_WORD_POOL.find((w) => w.word.toLowerCase() === key);
  const context = entry?.context || "General use";
  const hindiMeaning = HINDI_DICTIONARY[key] || word.charAt(0).toUpperCase() + word.slice(1);

  return {
    partOfSpeech: "verb",
    englishMeaning: `To perform or apply in practical scenarios (${context}).`,
    hindiMeaning,
    exampleSentence: `Understanding how to use "${word}" effectively improves everyday communication.`,
    pronunciation: `/${word}/`,
    synonyms: ["apply", "utilize"],
  };
}
